name: Build Madeira for LiveContainer

on:
  workflow_dispatch: # 允許手動點擊按鈕觸發編譯

jobs:
  build:
    runs-on: macos-14 # 使用 GitHub 官方免費的 macOS 雲端伺服器
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build Application
        run: |
          mkdir -p build
          xcodebuild -project Madeira.xcodeproj \
                     -scheme Madeira \
                     -configuration Release \
                     -sdk iphoneos \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGN_ING_REQUIRED=NO \
                     clean build
          
          # 將編譯產出的 .app 移至打包目錄
          mv build/Release-iphoneos/Madeira.app ./Madeira.app

      - name: Upload Artifact (Madeira.app)
        uses: actions/upload-artifact@v4
        with:
          name: Madeira-LiveContainer-App
          path: ./Madeira.app
