name: Build Madeira for LiveContainer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # 自動下載專案內可能包含的子模組

      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Find Project and Build
        run: |
          PROJ_PATH=$(find . -name "*.xcodeproj" -print -quit)
          echo "Found project at: $PROJ_PATH"
          
          mkdir -p build_output
          
          # 使用最寬鬆的隨機簽名參數強行推進
          xcodebuild -project "$PROJ_PATH" \
                     -scheme Madeira \
                     -configuration Release \
                     -sdk iphoneos \
                     CODE_SIGNING_ALLOWED=YES \
                     CODE_SIGNING_REQUIRED=NO \
                     CODE_SIGN_IDENTITY="-" \
                     -derivedDataPath build_output \
                     clean build

          APP_PATH=$(find build_output -name "Madeira.app" -type d -print -quit)
          mv "$APP_PATH" ./Madeira.app

      - name: Upload Artifact (Madeira.app)
        uses: actions/upload-artifact@v4
        with:
          name: Madeira-LiveContainer-App
          path: ./Madeira.app
